


export const ADD_SALE_REQUEST =  "ADD_SALE_REQUEST" 
export const ADD_SALE_SUCCESS =  "ADD_SALE_SUCCESS" 
export const ADD_SALE_FAILED =  "ADD_SALE_FAILED" 



export const FETCH_SALES_REQUEST = "FETCH_SALES_REQUEST"
export const FETCH_SALES_SUCCESS = "FETCH_SALES_SUCCESS"
export const FETCH_SALES_FAILED = "FETCH_SALES_FAILED"