

export const FETCH_CUSTOMER_GROUPS_REQUEST = "FETCH_CUSTOMER_GROUPS_REQUEST"
export const FETCH_CUSTOMER_GROUPS_SUCCESS = "FETCH_CUSTOMER_GROUPS_SUCCESS"
export const FETCH_CUSTOMER_GROUPS_FAILED = "FETCH_CUSTOMER_GROUPS_FAILED"



export const FETCH_CUSTOMERS_REQUEST = "FETCH_CUSTOMER_REQUEST"
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMER_SUCCESS"
export const FETCH_CUSTOMERS_FAILED = "FETCH_CUSTOMER_FAILED"


export const CREATE_CUSTOMER_GROUP_REQUEST = "CREATE_CUSTOMER_GROUP_REQUEST"
export const CREATE_CUSTOMER_GROUP_SUCCESS = "CREATE_CUSTOMER_GROUP_SUCCESS"
export const CREATE_CUSTOMER_GROUP_FAILED = "CREATE_CUSTOMER_GROUP_FAILED"



export const ADD_CUSTOMERS_TO_GROUP_REQUEST = "AAD_CUSTOMERS_TO_GROUP_REQUEST"
export const ADD_CUSTOMERS_TO_GROUP_SUCCESS = "AAD_CUSTOMERS_TO_GROUP_SUCCESS"
export const ADD_CUSTOMERS_TO_GROUP_FAILED = "AAD_CUSTOMERS_TO_GROUP_FAILED"