

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"


export const FETCH_PRODUCT_PIECES_REQUEST = "FETCH_PRODUCT_PIECES_REQUEST"
export const FETCH_PRODUCT_PIECES_SUCCESS = "FETCH_PRODUCT_PIECES_SUCCESS"
export const FETCH_PRODUCT_PIECES_FAILED = "FETCH_PRODUCT_PIECES_FAILED"